### ISSUE TITLE
Attempt to read from field 'android.view.WindowManager$LayoutParams android.view.ViewRootImpl.mWindowAttributes' on a null object reference

### ISSUE THREAD

**Issue by hisaichi5518** [hisaichi5518/native_webview#29]
Sometimes the app crashes.

```
D/AndroidRuntime( 8163): Shutting down VM
E/AndroidRuntime( 8163): FATAL EXCEPTION: main
E/AndroidRuntime( 8163): Process: ..., PID: 8163
E/AndroidRuntime( 8163): java.lang.NullPointerException: Attempt to read from field 'android.view.WindowManager$LayoutParams android.view.ViewRootImpl.mWindowAttributes' on a null object reference
E/AndroidRuntime( 8163): 	at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1626)
E/AndroidRuntime( 8163): 	at android.view.inputmethod.InputMethodManager.checkFocus(InputMethodManager.java:1865)
E/AndroidRuntime( 8163): 	at android.view.inputmethod.InputMethodManager.isActive(InputMethodManager.java:1184)
E/AndroidRuntime( 8163): 	at com.hisaichi5518.native_webview.InputAwareWebView$1.run(InputAwareWebView.java:204)
E/AndroidRuntime( 8163): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime( 8163): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime( 8163): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 8163): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime( 8163): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8163): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime( 8163): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

I haven't found a way to recreate it.

**Comment by hisaichi5518** [comment]
When I passed Activity to NativeWebView, it was reproduced.
```kotlin
webview = NativeWebView(methodChannel, Locator.activity!!, options)
```

Use context.
```kotlin
webview = NativeWebView(methodChannel, context, options)
```
